language: rust

rust:
  - stable
  - nightly

os:
  - linux
  - osx

script:
  - RUST_BACKTRACE=1 cargo test --verbose
  - if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then
      RUST_BACKTRACE=1 cargo bench --verbose;
    fi
