[package]
name = "asyncio"
version = "0.1.0"
edition = "2024"
license = "MIT"
authors = ["harre-orz <harre.orz@gmail.com>"]

[features]
default = ["timerfd", "ktimer"]
timerfd = []
eventfd = []
ktimer = []

[dependencies]
libc = "1.0.0-alpha.3"

[target.'cfg(windows)'.dependencies]
windows-sys = "0.61.2"

[dependencies.windows-sys]
version = "0.61.2"
features = ["Win32", "Win32_System_IO", "Win32_Storage_FileSystem", "Win32_Security", "Win32_System_Pipes", "Win32_Foundation", "Win32_Networking", "Win32_Networking_WinSock", "Win32_NetworkManagement", "Win32_NetworkManagement_IpHelper", "Win32_NetworkManagement_Ndis", "Win32_System_Diagnostics", "Win32_System_Diagnostics_Debug"]

[dev-dependencies]
chrono = "0.4.44"
futures = { version = "0.3.32" }
tokio = { version = "1.52.3", features = ["macros", "rt"] }
