[package]
name = "asyio"
version = "0.1.0"
edition = "2024"
authors = ["harre-orz <harre.orz@gmail.com>"]

[dependencies]
libc = "0.2.173"
openssl-sys = { version = "0.9.109", optional = true }

[target.'cfg(windows)'.dependencies]
windows-sys = "0.60.2"

[dependencies.windows-sys]
version = "0.60"
features = ["Win32_System_IO", "Win32", "Win32_Networking", "Win32_Networking_WinSock", "Win32_System_Diagnostics", "Win32_System_Diagnostics_Debug"]

[dev-dependencies]
chrono = "0.4.38"
futures = { version = "0.3.30" }
tokio = {version="~0.2", features=["macros", "rt-core"]}
