[package]
name = "asyncio"
version = "0.1.0"
edition = "2024"
license = "MIT"
authors = ["harre-orz <harre.orz@gmail.com>"]

[features]
default = ["intr", "poll"]
intr = ["intr_timerfd"]
poll = ["poll_epoll"]
intr_timerfd = []
intr_eventfd = []
intr_pipe = []
poll_kqueue = []
poll_epoll = []
poll_select = []

[dependencies]
libc = "1.0.0-alpha.3"
openssl-sys = { version = "0.9.115", optional = true }

[target.'cfg(windows)'.dependencies]
windows-sys = "0.61.2"

[dependencies.windows-sys]
version = "0.61.2"
features = ["Win32_System_IO", "Win32", "Win32_Networking", "Win32_Networking_WinSock", "Win32_System_Diagnostics", "Win32_System_Diagnostics_Debug"]

[dev-dependencies]
chrono = "0.4.44"
futures = { version = "0.3.32" }
tokio = {version="1.52.3", features=["macros", "rt"]}
